#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/pathfinding-robots
#-------------------------------------------------------------------------------

echo 'copying files' &&
mkdir -p "$HOME/.local/bin/" &&
cp src/pathfinding-robots.py "$HOME/.local/bin/"
