#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/pathfinding-robots
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f "$HOME/.local/bin/pathfinding-robots.py"
